.TH "/home/arvindbis29/Desktop/src/mantrana/build/CMakeFiles Directory Reference" 3 "Thu Nov 18 2021" "Version 1.0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/arvindbis29/Desktop/src/mantrana/build/CMakeFiles Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fB3\&.21\&.3\fP"
.br
.in -1c
