.TH "/home/arvindbis29/Desktop/src/mantrana/build/server/mantrana_server_autogen/4SSI3YASRV Directory Reference" 3 "Thu Nov 18 2021" "Version 1.0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/arvindbis29/Desktop/src/mantrana/build/server/mantrana_server_autogen/4SSI3YASRV Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBqrc_static\&.cpp\fP"
.br
.in -1c
