.TH "AuthDialog" 3 "Thu Nov 18 2021" "Version 1.0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AuthDialog
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AuthDialog\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBaccept\fP () override"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAuthDialog\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fBQ_DISABLE_COPY\fP (\fBAuthDialog\fP)"
.br
.ti -1c
.RI "\fB~AuthDialog\fP () override"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AuthDialog::AuthDialog (QWidget * parent = \fCnullptr\fP)\fC [explicit]\fP"

.SS "AuthDialog::~AuthDialog ()\fC [override]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void AuthDialog::accept ()\fC [override]\fP, \fC [slot]\fP"

.SS "AuthDialog::Q_DISABLE_COPY (\fBAuthDialog\fP)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
