.TH "/home/arvindbis29/Desktop/src/mantrana/client/AuthDialog.cpp" 3 "Thu Nov 18 2021" "Version 1.0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/arvindbis29/Desktop/src/mantrana/client/AuthDialog.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <QIcon>\fP
.br
\fC#include <QPushButton>\fP
.br
\fC#include 'AuthDialog\&.h'\fP
.br
\fC#include 'ui_AuthDialog\&.h'\fP
.br
\fC#include 'ChatWindow\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
