.TH "ChatConnection" 3 "Thu Nov 18 2021" "Version 1.0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChatConnection
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ChatConnection\&.h>\fP
.PP
Inherits \fBConnection\fP\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBchatMessage\fP (const QJsonObject &data)"
.br
.ti -1c
.RI "void \fBerrorMessage\fP (const QJsonObject &data)"
.br
.ti -1c
.RI "void \fBlogin\fP ()"
.br
.ti -1c
.RI "void \fBfail\fP (const QString &reason)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChatConnection\fP (const QString &urlString, QObject *parent=nullptr)"
.br
.RI "\fBConnection\fP constructor\&. "
.ti -1c
.RI "void \fBstart\fP (const QJsonObject &loginData)"
.br
.RI "Opens websocket connection\&. "
.ti -1c
.RI "void \fBsendMessage\fP (const QString &text)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ChatConnection::ChatConnection (const QString & urlString, QObject * parent = \fCnullptr\fP)\fC [inline]\fP, \fC [explicit]\fP"

.PP
\fBConnection\fP constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIurlString\fP Websocket server address 
.br
\fIloginData\fP Auth information 
.br
\fIparent\fP QT parent 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void ChatConnection::chatMessage (const QJsonObject & data)\fC [signal]\fP"

.SS "void ChatConnection::errorMessage (const QJsonObject & data)\fC [signal]\fP"

.SS "void ChatConnection::fail (const QString & reason)\fC [signal]\fP"

.SS "void ChatConnection::login ()\fC [signal]\fP"

.SS "void ChatConnection::sendMessage (const QString & text)"

.SS "void ChatConnection::start (const QJsonObject & loginData)"

.PP
Opens websocket connection\&. 
.PP
\fBParameters\fP
.RS 4
\fIloginData\fP Auto information 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
