.TH "ChatWindow" 3 "Thu Nov 18 2021" "Version 1.0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChatWindow
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ChatWindow\&.h>\fP
.PP
Inherits QMainWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChatWindow\fP (\fBChatConnection\fP *connection, QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fB~ChatWindow\fP () override"
.br
.ti -1c
.RI "void \fBinsertMessage\fP (const QString &message) const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ChatWindow::ChatWindow (\fBChatConnection\fP * connection, QWidget * parent = \fCnullptr\fP)"

.SS "ChatWindow::~ChatWindow ()\fC [override]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void ChatWindow::insertMessage (const QString & message) const"
< Messages
.PP
< Messages html

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
