.TH "/home/arvindbis29/Desktop/src/mantrana/client/ChatWindow.cpp" 3 "Thu Nov 18 2021" "Version 1.0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/arvindbis29/Desktop/src/mantrana/client/ChatWindow.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <QPushButton>\fP
.br
\fC#include <QtWebSockets/QWebSocket>\fP
.br
\fC#include <QPlainTextEdit>\fP
.br
\fC#include <QJsonArray>\fP
.br
\fC#include <QScrollBar>\fP
.br
\fC#include 'ChatConnection\&.h'\fP
.br
\fC#include 'ChatWindow\&.h'\fP
.br
\fC#include '\&./ui_ChatWindow\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
