.TH "Client" 3 "Thu Nov 18 2021" "Version 1.0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Client \- Basic client class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Client\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClient\fP (QWebSocket *socket, QObject *parent=nullptr)"
.br
.RI "Basic constructor from WS connection\&. "
.ti -1c
.RI "void \fBsendData\fP (const QString &type, const QJsonObject &data)"
.br
.RI "Sends data to client\&. "
.ti -1c
.RI "QWebSocket * \fBgetSocket\fP () const"
.br
.ti -1c
.RI "const QString & \fBgetName\fP () const"
.br
.ti -1c
.RI "\fBMessageHandler\fP * \fBgetMessageHandler\fP () const"
.br
.ti -1c
.RI "bool \fBisLogin\fP () const"
.br
.ti -1c
.RI "void \fBsetName\fP (const QString &clientName)"
.br
.ti -1c
.RI "void \fBsetLogin\fP (bool login)"
.br
.ti -1c
.RI "\fB~Client\fP () override"
.br
.in -1c
.SH "Detailed Description"
.PP 
Basic client class\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Client::Client (QWebSocket * socket, QObject * parent = \fCnullptr\fP)\fC [explicit]\fP"

.PP
Basic constructor from WS connection\&. 
.PP
\fBParameters\fP
.RS 4
\fIsocket\fP \fBConnection\fP 
.RE
.PP

.SS "Client::~Client ()\fC [inline]\fP, \fC [override]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBMessageHandler\fP * Client::getMessageHandler () const\fC [inline]\fP"

.SS "const QString & Client::getName () const\fC [inline]\fP"

.SS "QWebSocket * Client::getSocket () const\fC [inline]\fP"

.SS "bool Client::isLogin () const\fC [inline]\fP"

.SS "void Client::sendData (const QString & type, const QJsonObject & data)"

.PP
Sends data to client\&. 
.PP
\fBParameters\fP
.RS 4
\fItype\fP String type of sending data 
.br
\fIdata\fP Sending data 
.RE
.PP

.SS "void Client::setLogin (bool login)\fC [inline]\fP"

.SS "void Client::setName (const QString & clientName)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
