.TH "/home/arvindbis29/Desktop/src/mantrana/build/server/CMakeFiles/mantrana_server.dir/Config.cpp.o.d" 3 "Thu Nov 18 2021" "Version 1.0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/arvindbis29/Desktop/src/mantrana/build/server/CMakeFiles/mantrana_server.dir/Config.cpp.o.d
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
