.TH "/home/arvindbis29/Desktop/src/mantrana/server/Config.h" 3 "Thu Nov 18 2021" "Version 1.0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/arvindbis29/Desktop/src/mantrana/server/Config.h
.SH SYNOPSIS
.br
.PP
\fC#include <QJsonObject>\fP
.br
\fC#include <QFile>\fP
.br
\fC#include <QJsonDocument>\fP
.br
\fC#include <sstream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConfig\fP"
.br
.RI "\fBConfig\fP class\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
