.TH "/home/arvindbis29/Desktop/src/mantrana/client/Connection.h" 3 "Thu Nov 18 2021" "Version 1.0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/arvindbis29/Desktop/src/mantrana/client/Connection.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtWebSockets/QWebSocket>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConnection\fP"
.br
.RI "Basic connection class\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
