.TH "MessageHandler" 3 "Thu Nov 18 2021" "Version 1.0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MessageHandler \- Get and prepare message\&. Can be connected\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MessageHandler\&.h>\fP
.PP
Inherits QObject\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBonMessage\fP (const QString &type, const QJsonObject &json)"
.br
.RI "Triggers on message got\&. "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMessageHandler\fP (QObject *parent=nullptr)"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "void \fBgiveMessage\fP (const QString &message)"
.br
.RI "Send message from handler\&. "
.in -1c
.SH "Detailed Description"
.PP 
Get and prepare message\&. Can be connected\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MessageHandler::MessageHandler (QObject * parent = \fCnullptr\fP)\fC [explicit]\fP"

.PP
Default constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIparent\fP QT parent 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void MessageHandler::giveMessage (const QString & message)"

.PP
Send message from handler\&. 
.PP
\fBParameters\fP
.RS 4
\fImessage\fP String message 
.RE
.PP

.SS "void MessageHandler::onMessage (const QString & type, const QJsonObject & json)\fC [signal]\fP"

.PP
Triggers on message got\&. 
.PP
\fBParameters\fP
.RS 4
\fItype\fP Type of message 
.br
\fIjson\fP Message data 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
