.TH "/home/arvindbis29/Desktop/src/mantrana/build/server/mantrana_server_autogen/4SSI3YASRV/qrc_static.cpp" 3 "Thu Nov 18 2021" "Version 1.0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/arvindbis29/Desktop/src/mantrana/build/server/mantrana_server_autogen/4SSI3YASRV/qrc_static.cpp
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBQT_RCC_PREPEND_NAMESPACE\fP(name)   name"
.br
.ti -1c
.RI "#define \fBQT_RCC_MANGLE_NAMESPACE\fP(name)   name"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBqRegisterResourceData\fP (int, const unsigned char *, const unsigned char *, const unsigned char *)"
.br
.ti -1c
.RI "bool \fBqUnregisterResourceData\fP (int, const unsigned char *, const unsigned char *, const unsigned char *)"
.br
.ti -1c
.RI "unsigned char \fBqResourceFeatureZlib\fP ()"
.br
.ti -1c
.RI "int \fBQT_RCC_MANGLE_NAMESPACE\fP() \fBqInitResources_static\fP ()"
.br
.ti -1c
.RI "int \fBQT_RCC_MANGLE_NAMESPACE\fP() \fBqCleanupResources_static\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define QT_RCC_MANGLE_NAMESPACE(name)   name"

.SS "#define QT_RCC_PREPEND_NAMESPACE(name)   name"

.SH "Function Documentation"
.PP 
.SS "int \fBQT_RCC_MANGLE_NAMESPACE\fP() qCleanupResources_static ()"

.SS "int \fBQT_RCC_MANGLE_NAMESPACE\fP() qInitResources_static ()"

.SS "bool qRegisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)"

.SS "unsigned char qResourceFeatureZlib ()"

.SS "bool qUnregisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
