.TH "qt_meta_stringdata_AuthDialog_t" 3 "Thu Nov 18 2021" "Version 1.0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qt_meta_stringdata_AuthDialog_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QByteArrayData \fBdata\fP [3]"
.br
.ti -1c
.RI "char \fBstringdata0\fP [19]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "QByteArrayData qt_meta_stringdata_AuthDialog_t::data[3]"

.SS "char qt_meta_stringdata_AuthDialog_t::stringdata0[19]"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
