.TH "/home/arvindbis29/Desktop/src/mantrana/build/client/mantrana_client_autogen/include/ui_ChatWindow.h" 3 "Thu Nov 18 2021" "Version 1.0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/arvindbis29/Desktop/src/mantrana/build/client/mantrana_client_autogen/include/ui_ChatWindow.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QVariant>\fP
.br
\fC#include <QtGui/QIcon>\fP
.br
\fC#include <QtWidgets/QApplication>\fP
.br
\fC#include <QtWidgets/QHBoxLayout>\fP
.br
\fC#include <QtWidgets/QLineEdit>\fP
.br
\fC#include <QtWidgets/QMainWindow>\fP
.br
\fC#include <QtWidgets/QPushButton>\fP
.br
\fC#include <QtWidgets/QTextBrowser>\fP
.br
\fC#include <QtWidgets/QVBoxLayout>\fP
.br
\fC#include <QtWidgets/QWidget>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUi_ChatWindow\fP"
.br
.ti -1c
.RI "class \fBUi::ChatWindow\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
