.TH "Ui::ChatWindow" 3 "Thu Nov 18 2021" "Version 1.0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::ChatWindow
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ui_ChatWindow\&.h>\fP
.PP
Inherits \fBUi_ChatWindow\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
