.TH "/home/arvindbis29/Desktop/src/mantrana/server/WebSocketListener.h" 3 "Thu Nov 18 2021" "Version 1.0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/arvindbis29/Desktop/src/mantrana/server/WebSocketListener.h
.SH SYNOPSIS
.br
.PP
\fC#include <QSet>\fP
.br
\fC#include <QObject>\fP
.br
\fC#include <QtWebSockets/QWebSocket>\fP
.br
\fC#include <QtWebSockets/QWebSocketServer>\fP
.br
\fC#include 'Config\&.h'\fP
.br
\fC#include 'Client\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWebSocketListener\fP"
.br
.RI "Basic websocket listener\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
