.TH "WebSocketListener" 3 "Thu Nov 18 2021" "Version 1.0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WebSocketListener \- Basic websocket listener\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <WebSocketListener\&.h>\fP
.PP
Inherits QObject\&.
.PP
Inherited by \fBChatWebSocketListener\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWebSocketListener\fP (const \fBConfig\fP *config, QObject *parent=nullptr)"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "virtual void \fBstart\fP ()"
.br
.RI "Start the websocket server\&. "
.ti -1c
.RI "bool \fBisSocketAvailable\fP (QWebSocket *socket) const"
.br
.RI "Checks if socket exists, socket registered and is login\&. "
.ti -1c
.RI "\fB~WebSocketListener\fP () override"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBClient\fP * \fBonConnect\fP ()"
.br
.ti -1c
.RI "virtual void \fBonMessage\fP (const QString &message)"
.br
.ti -1c
.RI "virtual void \fBonDisconnect\fP ()"
.br
.ti -1c
.RI "void \fBsendDataToAll\fP (const QString &type, const QJsonObject &data)"
.br
.ti -1c
.RI "void \fBremoveClient\fP (\fBClient\fP *client)"
.br
.RI "Removes client from registered\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "QHash< QWebSocket *, \fBClient\fP * > \fBclients\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Basic websocket listener\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "WebSocketListener::WebSocketListener (const \fBConfig\fP * config, QObject * parent = \fCnullptr\fP)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Default constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIconfig\fP Configuration object 
.br
\fIparent\fP QT parent 
.RE
.PP

.SS "WebSocketListener::~WebSocketListener ()\fC [inline]\fP, \fC [override]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool WebSocketListener::isSocketAvailable (QWebSocket * socket) const\fC [inline]\fP"

.PP
Checks if socket exists, socket registered and is login\&. 
.PP
\fBParameters\fP
.RS 4
\fIsocket\fP \fBConnection\fP 
.RE
.PP
\fBReturns\fP
.RS 4
true, if checks have been passed 
.RE
.PP

.SS "\fBClient\fP * WebSocketListener::onConnect ()\fC [protected]\fP, \fC [virtual]\fP"
< \fBConnection\fP
.PP
< \fBClient\fP object
.PP
Reimplemented in \fBChatWebSocketListener\fP\&.
.SS "void WebSocketListener::onDisconnect ()\fC [protected]\fP, \fC [virtual]\fP"
< \fBConnection\fP
.PP
Reimplemented in \fBChatWebSocketListener\fP\&.
.SS "void WebSocketListener::onMessage (const QString & message)\fC [protected]\fP, \fC [virtual]\fP"
< \fBConnection\fP
.PP
Reimplemented in \fBChatWebSocketListener\fP\&.
.SS "void WebSocketListener::removeClient (\fBClient\fP * client)\fC [inline]\fP, \fC [protected]\fP"

.PP
Removes client from registered\&. 
.PP
\fBParameters\fP
.RS 4
\fIclient\fP \fBClient\fP object 
.RE
.PP

.SS "void WebSocketListener::sendDataToAll (const QString & type, const QJsonObject & data)\fC [protected]\fP"

.SS "void WebSocketListener::start ()\fC [virtual]\fP"

.PP
Start the websocket server\&. 
.SH "Member Data Documentation"
.PP 
.SS "QHash<QWebSocket *, \fBClient\fP *> WebSocketListener::clients\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
